NAME
  Visocyte::ClientServerCoreDefault
LIBRARY_NAME
  vtkPVClientServerCoreDefault
KIT
  Visocyte::ClientServerKit
DEPENDS
  Visocyte::ClientServerCoreRendering
  Visocyte::VTKExtensionsDefault

  # Only needed because of the vtkPythonInterpreter optional dependency.
  VTK::FiltersProgrammable
PRIVATE_DEPENDS
  VTK::IOInfovis
  VTK::vtksys
TEST_DEPENDS
  VTK::TestingCore
TEST_OPTIONAL_DEPENDS
  VTK::ParallelMPI
  VTK::Python

  # This is due to a public optional dependency in
  # Visocyte::VTKExtensionsRendering.
  Visocyte::icet
TEST_LABELS
  Visocyte
