NAME
  Visocyte::ServerManagerRendering
LIBRARY_NAME
  vtkPVServerManagerRendering
GROUPS
  VisocyteRendering
KIT
  Visocyte::ServerManager
IMPLEMENTS
  Visocyte::ServerManagerCore
DEPENDS
  Visocyte::ServerImplementationRendering
  Visocyte::ServerManagerCore
  VTK::jsoncpp
PRIVATE_DEPENDS
  VTK::CommonColor
  VTK::vtksys
OPTIONAL_DEPENDS
  VTK::RenderingOSPRay

  # These affect the public API.
  Visocyte::ClientServerCorePython
TEST_DEPENDS
  Visocyte::ServerManagerApplication
  VTK::TestingCore
TEST_LABELS
  Visocyte
